# Generated by Django 5.1.4 on 2026-03-29 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(help_text='Heart rate in beats per minute (bpm)')),
                ('sleep_hours', models.FloatField(help_text='Hours of sleep last night')),
                ('steps', models.IntegerField(help_text='Total steps walked today')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('score', models.FloatField(default=0.0, help_text='Computed health score (0–100)')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Predicted risk level: low / medium / high', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional user notes for this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Log',
                'verbose_name_plural': 'Health Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
